export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const GET_ALL_EMPLOYEES_STATUSES = 'GET_ALL_EMPLOYEES_STATUSES';
export const FETCH_STATUSES_DATA = 'FETCH_STATUSES_DATA';

export const FEATCH_STATUSES_TO_DISPALY = 'FEATCH_STATUSES_TO_DISPALY';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_BY_EMAIL = 'LOGIN_BY_EMAIL';
export const UPDATE_STATUS = 'UPDATE_STATUS';
